# docker-compose.yml
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
      - API_EMAIL="rdrgz.zrz.pdr@gmail.com"
    command:
      - "--api=true"
      - "--api.dashboard=true"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    #labels:
    #  # Dashboard router
    #  - "traefik.http.routers.dashboard.rule=Host(`paninimania.cloud`) && PathPrefix(`/dashboard`)"
    #  - "traefik.http.routers.dashboard.entrypoints=web"
    #  - "traefik.http.routers.dashboard.service=api@internal"
    #  - "traefik.http.routers.dashboard.tls=true"

      # Basic‑auth middleware
    #  - "traefik.http.middlewares.dashboard-auth.asicauth.users=admin:$$apr1$$WRYAi2h3$$poREBMtapOOPXP5LegF/8."
    #  - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
  whoiam:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoiam.rule=Host(`paninimania.cloud`) && PathPrefix(`/whoiam`)"
    networks:
      - proxy
networks:
  proxy:
    name: proxy
    driver: bridge
