# docker-compose.yml
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
      - API_EMAIL="rdrgz.zrz.pdr@gmail.com"
    command:
    #  - "--api.insecure=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`paninimania.cloud`) && PathPrefix(`/dashboard`)"

      #- "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$WRYAi2h3$$poREBMtapOOPXP5LegF/8."
      #- "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
  whoiam:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoiam.rule=Host(`paninimania.cloud`)"
    networks:
      - proxy
networks:
  proxy:
    name: proxy
    driver: bridge
