api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: ":80"
    #http:
    #  redirections:
    #    entryPoint:
    #      to: websecure
    #      scheme: https
          #permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt-staging
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
  file:
    filename: /config.yml
certificatesResolvers:
  letsencrypt:
    acme:
      email: rdrgz.zrz.pdr@gmail.com
      httpChallenge:
        entryPoint: web
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
      caServer: https://acme-v02.api.letsencrypt.org/directory
  letsencrypt-staging:
    acme:
      email: rdrgz.zrz.pdr@gmail.com
      httpChallenge:
        entryPoint: web
      storage: /etc/traefik/acme-staging
      tlsChallenge: {}
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
  myresolver:
    acme:
      #caServer: https://acme-v02.api.letsencrypt.org/directory
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: rdrgz.zrz.pdr@gmail.com
      storage: acme.json
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: hostinguer
        # used during the challenge
        resolvers:
          - "aster.dns-parking.com"
          - "helios.dns-parking.com"